//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestXml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestXml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;S2SCTScf:SCTIcfBlkCredTrf xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:S2SCTScf=&quot;urn:S2SCTIcf:xsd:$SCTIcfBlkCredTrf&quot;&gt;
        ///&lt;S2SCTScf:SndgInst&gt;BNDANL2A&lt;/S2SCTScf:SndgInst&gt;
        ///&lt;S2SCTScf:RcvgInst&gt;ABNANL2A&lt;/S2SCTScf:RcvgInst&gt;
        ///&lt;S2SCTScf:FileRef&gt;BNDA201605250013&lt;/S2SCTScf:FileRef&gt;
        ///&lt;S2SCTScf:SrvcId&gt;SCT&lt;/S2SCTScf:SrvcId&gt;
        ///&lt;S2SCTScf:TstCode&gt;P&lt;/S2SCTScf:TstCode&gt;
        ///&lt;S2SCTScf:FType&gt;ICF&lt;/S2SCTScf:FType&gt;
        ///&lt;S2SCTScf:FDtTm&gt;2016- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2016_05_25T14_34_10_891_BNDA201605250013 {
            get {
                return ResourceManager.GetString("_2016_05_25T14_34_10_891_BNDA201605250013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] payment200313_xml {
            get {
                object obj = ResourceManager.GetObject("payment200313_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
